### ISSUE TITLE
value ranges?

### ISSUE THREAD

**Issue by nohkumado** [frankpepermans/fast_noise#7]
Hello!
no discussion area, so posting an issue, sorry for the pollution....

just wondering, i was expecting from the noise2 function values between 0 and 1, but the values are between -1 and 1 (actually my longest run yielded from -.6 to .6 which seems strange to me)?

Is there a way to change this? 
to force the spread over the whole range?

**Comment by spydon** [comment]
Hey there,
which noise class were you using?

**Comment by nohkumado** [comment]
ah seems i i am lacking understanding in more than one area :D 

i was using this:
`var altnoise2d = noise2(width+1,height+1,noiseType: NoiseType.perlin, octaves: 3, frequency: 0.05, seed: seed??DateTime.now().millisecondsSinceEpoch );`

**Comment by spydon** [comment]
Ah right, forgot we had that helper. :)
So you're using the `PerlinNoise` class and perlin noise usually goes between [-1, 1], if you want it to go between [0,1] you can easily just change it afterwards with something like:
```dart
var altnoise2d = noise2(width+1,height+1,noiseType: NoiseType.perlin, octaves: 3, frequency: 0.05, seed: seed);
altnoise2d *= altnoise2d.isNegative ? -1 : 1;
```

Maybe it is not a [perlin noise](https://en.wikipedia.org/wiki/Perlin_noise) that you are looking for?

**Comment by nohkumado** [comment]
:D I admit my ignorance concerning noise, I wanted to generate a game map and was following the excellent article on redblob games that proposed the perlin noise, but if you think that another type would be better suited I will be happy to try that one out!

**Comment by spydon** [comment]
Perlin noise is a classic for something like that, so it's a good one to start with :)

**Comment by nohkumado** [comment]
So, just to close up, different noise functions result in different result ranges?
Means that in my code I should always normalize before using?

**Comment by spydon** [comment]
I think that all our noise classes go from -1 to 1, but remember that it isn't an even distribution like it would be with random numbers for example.

**Comment by nohkumado** [comment]
Ok, thanks!
